### ISSUE TITLE
map configuration

### ISSUE THREAD

**Issue by zhaishengfu** [RaceTheMaSe/UtyMapUnreal#3]
hello， with your help now i can compile unreal project right， but what should i set the configuration of uty map configuration??there are three file: map data, map css and index folder. Please tell me how to get these files and set them correcttly(I know it is openstreetmap, but how?)Thank you advance
I set the map data file as string, map css file as string and index folder, and when play it corrupted So I ask you how to set them. my set is:
map data file as string:E:\415\unrealenvironments\utymap-master\utymap-master\unity\demo\Assets\StreamingAssets\Osm\berlin.osm.xml
and so on

**Comment by RaceTheMaSe** [comment]
I guess you figured it out to set them to the right directories from Utymap-Unity.

A common crash could be in delayhlp.cpp, which means that you need to copy the UtyMap.shared.dll and zlibd.dll into <Utymap-Unreal-Project>/Binaries/Win64
The crash I am thinking of occurs on the first call into Utymap library in CoreLibrary.cpp: configure(IndexFolderPath.c_str(), OnError);

**Comment by zhaishengfu** [comment]
Thank you very much. You are right. Now I can run the program correctly. The last question: where should I change If I want to change the mesh to my custom static mesh??(trees,  buildings and streets?).

**Comment by RaceTheMaSe** [comment]
Look at issue #2 for my answer on custom meshes :-)
